import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { SUBJECTS, CURRICULUM, tasksForDay } from "@/services/study-plan";

export const Route=createFileRoute("/exercicios")({component:Exercicios});

type Q={id:string;subject:string;topic:string;prompt:string;options:string[];answer:number;explanation:string};
const questions:Q[]=SUBJECTS.filter(s=>s!=="Redação").flatMap(subject=>CURRICULUM[subject].slice(0,3).map((topic,i)=>({id:`${subject}-${i}`,subject,topic,prompt:`Questão de prática: qual é o principal conceito que você deve dominar em ${topic}?`,options:[`Reconhecer e aplicar o conceito em problemas`,"Memorizar sem compreender",`Ignorar exemplos e exercícios`,`Estudar apenas definições`],answer:0,explanation:`A preparação deve priorizar compreensão e aplicação de ${topic}.`})));

function Exercicios(){const [subject,setSubject]=useState("Todos"),[index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[score,setScore]=useState(0);const list=useMemo(()=>subject==="Todos"?questions:questions.filter(q=>q.subject===subject),[subject]);const q=list[index%Math.max(1,list.length)];function answer(i:number){if(selected!==null)return;setSelected(i);if(i===q.answer)setScore(s=>s+1)}function next(){setSelected(null);setIndex(i=>i+1)}return <main className="min-h-screen bg-slate-950 p-4 text-slate-100 sm:p-8"><div className="mx-auto max-w-4xl"><a href="/" className="text-sm text-indigo-300">← Voltar ao plano</a><h1 className="mt-5 text-3xl font-black">Exercícios</h1><p className="mt-2 text-slate-400">Pratique os conteúdos do edital e veja a explicação imediatamente.</p><select value={subject} onChange={e=>{setSubject(e.target.value);setIndex(0);setSelected(null)}} className="mt-5 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3">{["Todos",...SUBJECTS.filter(s=>s!=="Redação")].map(s=><option key={s}>{s}</option>)}</select>{q&&<section className="mt-5 rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div className="text-xs uppercase text-indigo-300">{q.subject} · {q.topic}</div><h2 className="mt-4 text-xl font-bold">{q.prompt}</h2><div className="mt-5 space-y-3">{q.options.map((o,i)=><button key={i} onClick={()=>answer(i)} className={`block w-full rounded-xl border p-4 text-left ${selected===i?(i===q.answer?"border-emerald-500 bg-emerald-500/10":"border-red-500 bg-red-500/10"):"border-slate-700 hover:border-indigo-500"}`}>{String.fromCharCode(65+i)}) {o}</button>)}</div>{selected!==null&&<div className="mt-5 rounded-xl bg-slate-800 p-4 text-sm"><b>{selected===q.answer?"Acertou!":"Revise este ponto."}</b><p className="mt-1 text-slate-300">{q.explanation}</p><button onClick={next} className="mt-4 rounded-lg bg-indigo-500 px-4 py-2 font-semibold">Próxima</button></div>}</section>}<div className="mt-5 text-sm text-slate-500">Acertos nesta sessão: {score}</div></div></main>}
