import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { SUBJECTS, CURRICULUM } from "@/services/study-plan";
export const Route=createFileRoute("/exercicios")({component:Exercicios});
type Q={id:string;subject:string;topic:string;prompt:string;options:string[];answer:number;explanation:string};
type Attempt={questionId:string;subject:string;topic:string;selected:number;correct:boolean;answeredAt:string};
const questions:Q[]=SUBJECTS.filter(s=>s!=="Redação").flatMap(subject=>CURRICULUM[subject].map((topic,i)=>({id:`${subject}-${i}`,subject,topic,prompt:`Qual é a melhor forma de estudar ${topic}?`,options:["Compreender o conceito e aplicá-lo em questões","Memorizar sem entender","Ignorar exemplos","Estudar somente na véspera"],answer:0,explanation:`Para o vestibular, o objetivo é compreender e aplicar o conteúdo de ${topic}.`})));
const userKey=()=>{if(typeof window==="undefined")return"anonymous";return localStorage.getItem("aprova-user-id")||localStorage.getItem("userId")||"local-device"};
const key=()=>`aprova-question-attempts:${userKey()}`;
function load():Attempt[]{try{return JSON.parse(localStorage.getItem(key())||"[]")}catch{return[]}}
function save(a:Attempt[]){localStorage.setItem(key(),JSON.stringify(a));}
function Exercicios(){const [subject,setSubject]=useState("Todos"),[index,setIndex]=useState(0),[selected,setSelected]=useState<number|null>(null),[attempts,setAttempts]=useState<Attempt[]>(load);const list=useMemo(()=>subject==="Todos"?questions:questions.filter(q=>q.subject===subject),[subject]);const q=list[index%Math.max(1,list.length)]!;function answer(i:number){if(selected!==null)return;setSelected(i);const a:Attempt={questionId:q.id,subject:q.subject,topic:q.topic,selected:i,correct:i===q.answer,answeredAt:new Date().toISOString()};const next=[...attempts.filter(x=>x.questionId!==q.id),a];setAttempts(next);save(next)}function next(){setSelected(null);setIndex(i=>i+1)}const correct=attempts.filter(a=>a.correct).length;return <main className="min-h-screen bg-slate-950 p-4 text-slate-100 sm:p-8"><div className="mx-auto max-w-5xl"><a href="/" className="text-sm text-indigo-300">← Voltar ao plano</a><div className="mb-6"><h1 className="mt-5 text-3xl font-black">Exercícios</h1><p className="mt-2 text-slate-400">Questões de todos os tópicos do edital, correção imediata e histórico por usuário.</p></div><div className="mb-5 flex flex-wrap gap-2">{["Todos",...SUBJECTS.filter(s=>s!=="Redação")].map(s=><button key={s} onClick={()=>{setSubject(s);setIndex(0);setSelected(null)}} className={`rounded-xl px-3 py-2 text-xs font-semibold ${subject===s?"bg-indigo-500":"bg-slate-800"}`}>{s}</button>)}</div><section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex justify-between text-xs text-slate-500"><span>{q.subject} · {q.topic}</span><span>{attempts.length} respondidas · {correct} acertos</span></div><h2 className="mt-5 text-xl font-bold">{q.prompt}</h2><div className="mt-5 space-y-3">{q.options.map((o,i)=><button key={i} onClick={()=>answer(i)} disabled={selected!==null} className={`w-full rounded-xl border p-4 text-left ${selected===i?(i===q.answer?"border-emerald-500 bg-emerald-500/10":"border-red-500 bg-red-500/10"):"border-slate-700 hover:border-indigo-500"}`}>{String.fromCharCode(65+i)}) {o}</button>)}</div>{selected!==null&&<div className="mt-5 rounded-xl bg-slate-800 p-4 text-sm"><b>{selected===q.answer?"Acertou!":"Errou — entrou no seu histórico de erros."}</b><p className="mt-2 text-slate-300">{q.explanation}</p><button onClick={next} className="mt-4 rounded-lg bg-indigo-500 px-4 py-2 font-semibold">Próxima</button></div>}</section></div></main>}
