import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";

export const Route = createFileRoute("/")({ component: AprovaUnimar });
type View="dashboard"|"roteiro"|"calendario"|"conteudos"|"aula"|"exercicios"|"simulados"|"redacao"|"tutor"|"erros"|"progresso";
type Attempt={topic:string;question:string;answer:string;correct:boolean;at:string};
type Q={id:string;prompt:string;options:string[];correct:number;explanation:string};
type Lesson={subject:string;topic:string;title:string;duration:string;video:string;videoId:string;why:string;questions:Q[]};
const EXAM="18/10/2026";
const lessons:Lesson[]=[
 {subject:"Português",topic:"Compreensão de texto",title:"Compreensão de textos: estratégia e questões",duration:"18 min",video:"Enem | Exercícios de Compreensão de Textos - Aula 1",videoId:"O0TTbXCTg-I",why:"Compreensão é a base para interpretar enunciados e textos antes de avançar para gramática.",questions:[{id:"pt1",prompt:"Na compreensão de texto, qual informação você deve procurar primeiro?",options:["Uma opinião pessoal","Uma informação explícita no texto","Uma regra gramatical","Uma informação que não aparece"],correct:1,explanation:"Comece pelo que o texto efetivamente apresenta; depois faça inferências."},{id:"pt2",prompt:"Se uma palavra é desconhecida, a melhor estratégia inicial é:",options:["Ignorá-la sempre","Procurar o sentido pelo contexto","Escolher o significado mais difícil","Inventar uma definição"],correct:1,explanation:"O contexto fornece pistas para compreender o vocabulário."}]},
 {subject:"Matemática",topic:"Frações",title:"Frações: conceitos e operações básicas",duration:"25 min",video:"Matemática Básica - Aula 13 - Frações (parte 1)",videoId:"i2GEeGSrZ_E",why:"Frações são pré-requisito para porcentagem, razão, proporção e muitos problemas de vestibular.",questions:[{id:"m1",prompt:"Qual é maior?",options:["2/3","3/4","1/2","3/5"],correct:1,explanation:"3/4 = 0,75 e 2/3 ≈ 0,67; portanto 3/4 é maior."},{id:"m2",prompt:"Uma fração equivalente a 2/3 é:",options:["3/5","4/6","5/8","6/8"],correct:1,explanation:"Multiplicando numerador e denominador por 2, obtemos 4/6."}]},
 {subject:"Biologia",topic:"Célula",title:"Célula e organização da vida",duration:"—",video:"Recurso em curadoria",videoId:"",why:"A célula é a base para metabolismo, divisão celular e genética. O app não exibirá vídeo aleatório.",questions:[{id:"b1",prompt:"Qual organela está diretamente relacionada à produção de ATP na respiração celular?",options:["Mitocôndria","Ribossomo","Lisossomo","Centríolo"],correct:0,explanation:"A mitocôndria é o principal local de produção de ATP na respiração aeróbica."}]}
];
const dailyPlan=[
 ["27/08","DIA 1","Compreensão de texto + frações + célula","Aula → vídeo → exercícios → registro de erros."],["28/08","DIA 2","Classes de palavras + frações equivalentes","Substantivo, artigo, adjetivo e numeral → prática → revisão."],["29/08","DIA 3","Pronomes, verbos + MMC","Classes em frases → MMC → operações com frações."],["30/08","DIA 4","Revisão D+1 + questões","Revisar erros e resolver bateria curta."],["31/08","DIA 5","Porcentagem + advérbio/preposição","Base de porcentagem → classificação → exercícios."],["01/09","DIA 6","Célula: organelas + aplicação","Revisar organelas → exercícios → erros."],["02/09","DIA 7","Revisão semanal + redação","Pontos fracos → 10 questões → estruturar redação."]
];
const schedule=[["08:00–08:30",0,"Aula","Compreensão de texto","Entender informação explícita, tema e ideia principal."],["08:30–08:50",0,"Prática","Português","Exercícios imediatamente após a aula."],["09:00–09:30",1,"Aula","Frações","Relembrar significado e comparação de frações."],["09:30–09:50",1,"Prática","Matemática","Exercícios imediatamente após a aula."],["10:00–10:30",2,"Aula","Célula","Reconhecer célula e estruturas principais."],["10:30–10:50",2,"Prática","Biologia","Exercício de fixação e registro de erros."],["19:00–19:20",0,"Revisão","Caderno de erros","Revisar dúvidas e erros do estudo."]] as const;
const mins=(s:string)=>{const [h,m]=s.split(":").map(Number);return (h||0)*60+(m||0)};
const status=(r:string,n:number)=>{const [a,b]=r.split("–");if(n<mins(a!))return"upcoming";if(n<=mins(b!))return"now";return"past"};
const clock=()=>new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit"}).format(new Date());
const read=(k:string,d:any)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
function AprovaUnimar(){
 const [view,setView]=useState<View>("dashboard"),[attempts,setAttempts]=useState<Attempt[]>(()=>read("aprova-attempts",[])),[li,setLi]=useState(0),[qi,setQi]=useState(0),[selected,setSelected]=useState<number|null>(null),[checked,setChecked]=useState(false),[done,setDone]=useState<Record<string,boolean>>(()=>read("aprova-lessons",{})),[essay,setEssay]=useState(()=>localStorage.getItem("aprova-essay")||""),[tutor,setTutor]=useState(""),[sim,setSim]=useState(false),[answers,setAnswers]=useState<Record<string,number>>({}),[now,setNow]=useState(new Date());
 useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(id)},[]);
 const lesson=lessons[li]!,q=lesson.questions[qi]!,errors=useMemo(()=>attempts.filter(x=>!x.correct),[attempts]),accuracy=attempts.length?Math.round(attempts.filter(x=>x.correct).length/attempts.length*100):0;
 const open=(i:number)=>{setLi(i);setQi(0);setSelected(null);setChecked(false);setView("aula")};
 const finishLesson=()=>{const d={...done,[lesson.topic]:true};setDone(d);localStorage.setItem("aprova-lessons",JSON.stringify(d));setQi(0);setSelected(null);setChecked(false);setView("exercicios")};
 const answer=()=>{if(selected===null||checked)return;const ok=selected===q.correct;const a=[...attempts,{topic:lesson.topic,question:q.prompt,answer:q.options[selected]!,correct:ok,at:new Date().toISOString()}];setAttempts(a);localStorage.setItem("aprova-attempts",JSON.stringify(a));setChecked(true)};
 const nav:[View,string][]=[["dashboard","Dashboard"],["roteiro","Roteiro de amanhã"],["calendario","Calendário"],["conteudos","Conteúdos"],["aula","Aulas + vídeos"],["exercicios","Exercícios"],["simulados","Simulados"],["redacao","Redação"],["tutor","Tutor IA"],["erros","Caderno de erros"],["progresso","Progresso"]];
 return <div className="min-h-screen bg-slate-950 text-slate-100"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-slate-800 p-5 lg:block"><div className="mb-8 text-2xl font-black">APROVA <span className="text-indigo-400">UNIMAR</span><div className="mt-1 text-xs font-normal text-slate-500">27/08 → 18/10 · Vestibular 2027</div></div>{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`mb-1 w-full rounded-xl px-3 py-2 text-left text-sm ${view===id?"bg-indigo-500/15 text-indigo-300":"text-slate-400 hover:bg-slate-900"}`}>{label}</button>)}<div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-slate-800 bg-slate-900 p-4 text-sm"><span className="text-slate-500">Prova</span><br/>{EXAM}<div className="text-xs text-slate-500">09:00–13:00 · Brasília</div></div></aside><main className="min-h-screen lg:ml-64"><header className="sticky top-0 z-10 border-b border-slate-800 bg-slate-950/95 px-4 py-4 backdrop-blur"><div className="text-xs font-medium text-indigo-300">SEMANA 1 · DIA 1</div><div className="flex justify-between"><div><h1 className="text-xl font-bold">26 de agosto · preparação</h1><div className="text-xs text-slate-500">Agora são <b className="text-slate-300">{clock()}</b></div></div><div className="text-xs text-slate-500">Prova: <b className="text-slate-200">{EXAM}</b></div></div></header><div className="border-b border-slate-800 p-2 lg:hidden overflow-x-auto"><div className="flex min-w-max gap-2">{nav.map(([id,label])=><button key={id} onClick={()=>setView(id)} className="rounded-lg bg-slate-800 px-3 py-1.5 text-xs">{label}</button>)}</div></div><div className="mx-auto max-w-7xl p-4 lg:p-8">
 {view==="dashboard"&&<Dashboard setView={setView} open={open} attempts={attempts} errors={errors} accuracy={accuracy} done={done}/>} 
 {view==="roteiro"&&<Roadmap now={now} open={open} setView={setView}/>} 
 {view==="calendario"&&<Section title="Calendário" sub="O estudo começa em 27/08. 26/08 não gera atraso."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{dailyPlan.map(x=><Card key={x[0]}><div className="flex justify-between"><b>{x[0]}/2026</b><span className="text-xs text-indigo-300">{x[1]}</span></div><h3 className="mt-3 font-semibold">{x[2]}</h3><p className="mt-2 text-sm text-slate-400">{x[3]}</p></Card>)}</div></Section>}
 {view==="conteudos"&&<Section title="Conteúdos" sub="Aprender → vídeo → exercícios → revisão → teste."><div className="grid gap-4 md:grid-cols-3">{lessons.map((l,i)=><Card key={l.topic}><span className="text-xs text-indigo-300">{l.subject}</span><h3 className="mt-2 font-semibold">{l.topic}</h3><p className="mt-2 text-sm text-slate-400">{l.why}</p><button onClick={()=>open(i)} className="mt-4 rounded-xl bg-indigo-500 px-4 py-2 text-sm">Abrir aula</button></Card>)}</div></Section>}
 {view==="aula"&&<Section title={lesson.title} sub={`${lesson.subject} · ${lesson.duration}`}><Card><p className="text-slate-300">{lesson.why}</p>{lesson.videoId?<div className="mt-5 aspect-video overflow-hidden rounded-2xl"><iframe className="h-full w-full" src={`https://www.youtube.com/embed/${lesson.videoId}`} title={lesson.video} allowFullScreen/></div>:<div className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm text-amber-200">Vídeo em curadoria. Não será usado vídeo aleatório.</div>}<button onClick={finishLesson} className="mt-5 rounded-xl bg-indigo-500 px-5 py-3 font-semibold">Concluí a aula → exercícios</button></Card></Section>}
 {view==="exercicios"&&<Section title={`Exercícios · ${lesson.topic}`} sub={`Questão ${qi+1}/${lesson.questions.length} · conteúdo recém-estudado`}><Card><h3 className="text-xl font-bold">{q.prompt}</h3><div className="mt-5 space-y-2">{q.options.map((o,i)=><button key={o} onClick={()=>!checked&&setSelected(i)} className={`w-full rounded-xl border p-3 text-left ${selected===i?"border-indigo-500 bg-indigo-500/10":"border-slate-700"}`}>{String.fromCharCode(65+i)}) {o}</button>)}</div>{checked&&<div className={`mt-5 rounded-xl p-4 ${selected===q.correct?"bg-emerald-500/10 text-emerald-200":"bg-red-500/10 text-red-200"}`}><b>{selected===q.correct?"CORRETO":"INCORRETO"}</b><p className="mt-2 text-sm">{q.explanation}</p></div>}<button disabled={selected===null&&!checked} onClick={()=>{if(!checked)answer();else if(qi<lesson.questions.length-1){setQi(qi+1);setSelected(null);setChecked(false)}else setView("aula")}} className="mt-5 rounded-xl bg-indigo-500 px-5 py-3 font-semibold disabled:opacity-40">{checked?(qi<lesson.questions.length-1?"Próxima questão":"Finalizar prática"):"Corrigir resposta"}</button></Card></Section>}
 {view==="simulados"&&<Simulation sim={sim} setSim={setSim} answers={answers} setAnswers={setAnswers}/>} 
 {view==="redacao"&&<Section title="Redação" sub="Escreva e salve seu texto. A correção IA será ligada ao backend seguro quando o provedor estiver configurado."><Card><b>Tema de treino</b><p className="mt-2 text-sm text-slate-300">Educação e tecnologia: desafios para a formação do estudante.</p><textarea value={essay} onChange={e=>setEssay(e.target.value)} className="mt-4 min-h-80 w-full rounded-xl border border-slate-700 bg-slate-900 p-4" placeholder="Escreva sua redação..."/><button onClick={()=>localStorage.setItem("aprova-essay",essay)} className="mt-3 rounded-xl bg-indigo-500 px-4 py-2">Salvar rascunho</button></Card></Section>}
 {view==="tutor"&&<Section title="Tutor IA" sub="Pergunte sobre o conteúdo que está estudando."><Card><textarea value={tutor} onChange={e=>setTutor(e.target.value)} className="min-h-32 w-full rounded-xl border border-slate-700 bg-slate-900 p-4" placeholder="Ex.: não entendi MMC..."/><p className="mt-3 text-sm text-amber-200">A resposta real depende da configuração segura do provedor de IA no backend.</p><button disabled={!tutor.trim()} className="mt-3 rounded-xl bg-indigo-500 px-5 py-3 disabled:opacity-40">Enviar dúvida</button></Card></Section>}
 {view==="erros"&&<Section title="Caderno de erros" sub="Somente respostas reais aparecem aqui.">{errors.length?errors.map((e,i)=><Card key={i} className="mb-3"><span className="text-xs text-indigo-300">{e.topic}</span><p className="mt-1 font-semibold">{e.question}</p><p className="mt-2 text-sm text-red-300">Sua resposta: {e.answer}</p></Card>):<Empty text="Ainda não há erros registrados."/>}</Section>}
 {view==="progresso"&&<Section title="Progresso" sub="Baseado somente em ações realizadas."><div className="grid gap-4 sm:grid-cols-3"><Metric label="Questões" value={String(attempts.length)}/><Metric label="Acerto" value={`${accuracy}%`}/><Metric label="Erros" value={String(errors.length)}/></div></Section>}
 </div></main></div>
}
function Dashboard({setView,open,attempts,errors,accuracy,done}:{setView:(v:View)=>void;open:(i:number)=>void;attempts:Attempt[];errors:Attempt[];accuracy:number;done:Record<string,boolean>}){return <div className="space-y-6"><div className="rounded-3xl border border-indigo-500/20 bg-indigo-500/10 p-6"><span className="text-sm text-indigo-300">26/08/2026 · PREPARAÇÃO</span><h2 className="mt-2 text-3xl font-black">Hoje não conta como atraso.</h2><p className="mt-2 text-slate-300">Seu primeiro dia real de estudos é amanhã, <b>27/08/2026</b>. O conteúdo será distribuído até a prova em 18/10.</p><button onClick={()=>setView("roteiro")} className="mt-5 rounded-xl bg-indigo-500 px-5 py-3 font-semibold">Ver roteiro de amanhã</button></div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Questões respondidas" value={String(attempts.length)}/><Metric label="Taxa de acerto" value={`${accuracy}%`}/><Metric label="Erros para revisar" value={String(errors.length)}/></div><Section title="Primeiras aulas" sub="Vídeo curado → exercícios imediatamente."><div className="grid gap-4 md:grid-cols-3">{lessons.map((l,i)=><Card key={l.topic}><span className="text-xs text-indigo-300">{l.subject}</span><h3 className="mt-2 font-semibold">{l.topic}</h3><button onClick={()=>open(i)} className="mt-4 text-sm text-indigo-300">Abrir →</button></Card>)}</div></Section></div>}
function Roadmap({now,open,setView}:{now:Date;open:(i:number)=>void;setView:(v:View)=>void}){const n=now.getHours()*60+now.getMinutes();const next=schedule.findIndex(x=>status(x[0],n)==="upcoming");return <Section title="Roteiro de amanhã · 27/08" sub={`Semana 1 · Dia 1 · horário local · agora ${clock()}`}><Card><b className="text-indigo-300">Primeiro dia real de estudo</b><p className="mt-2 text-sm text-slate-400">Hoje é apenas preparação. Amanhã o roteiro começa. Os horários abaixo são referências; o status acompanha o relógio do dispositivo.</p></Card><div className="mt-4 space-y-3">{schedule.map(([time,i,type,topic,desc],idx)=>{const st=status(time,n);return <Card key={time} className={st==="now"?"border-indigo-500/60 bg-indigo-500/10":st==="past"?"opacity-50":""}><div className="grid gap-3 md:grid-cols-[150px_1fr_auto] md:items-center"><b className="text-sm">{st==="now"?"AGORA · ":st==="past"?"ENCERRADO · ":"PRÓXIMO · "}{time}</b><div><span className="text-xs text-slate-500">{type}</span><div className="font-semibold">{topic}</div><p className="text-sm text-slate-400">{desc}</p></div>{type==="Prática"?<button onClick={()=>{setView("exercicios");open(i)}} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">Praticar</button>:type==="Revisão"?<button onClick={()=>setView("erros")} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">Revisar</button>:<button onClick={()=>open(i)} className="rounded-xl bg-indigo-500 px-4 py-2 text-sm">Estudar</button>}</div></Card>})}</div>{next<0&&<Card className="mt-4 border-emerald-500/20"><b className="text-emerald-300">Roteiro encerrado</b><p className="mt-2 text-sm text-slate-400">Quando chegar o próximo dia, o plano avança automaticamente.</p></Card>}<Card className="mt-4"><b className="text-emerald-300">Objetivo final</b><p className="mt-2 text-sm text-slate-400">Base → consolidação → vestibular → exercícios → simulados → revisão final até 18/10.</p></Card></Section>}
function Simulation({sim,setSim,answers,setAnswers}:{sim:boolean;setSim:(x:boolean)=>void;answers:Record<string,number>;setAnswers:(x:Record<string,number>)=>void}){const qs=lessons.flatMap(l=>l.questions);if(!sim)return <Section title="Simulados" sub="Prova dentro do app, sem substituir por vídeo."><Card><b>Simulado diagnóstico</b><p className="mt-2 text-sm text-slate-400">{qs.length} questões.</p><button onClick={()=>setSim(true)} className="mt-4 rounded-xl bg-indigo-500 px-5 py-3">Começar simulado</button></Card></Section>;return <Section title="Simulado em andamento" sub={`${Object.keys(answers).length}/${qs.length} respondidas`}><div className="space-y-3">{qs.map((q,i)=><Card key={q.id}><b>{i+1}. {q.prompt}</b><div className="mt-3 grid gap-2">{q.options.map((o,j)=><button key={o} onClick={()=>setAnswers({...answers,[q.id]:j})} className={`rounded-xl border p-3 text-left ${answers[q.id]===j?"border-indigo-500":"border-slate-700"}`}>{String.fromCharCode(65+j)}) {o}</button>)}</div></Card>)}</div><button onClick={()=>{const s=qs.reduce((a,q)=>a+(answers[q.id]===q.correct?1:0),0);alert(`Resultado: ${s}/${qs.length} (${Math.round(s/qs.length*100)}%)`);setSim(false)}} className="mt-5 rounded-xl bg-indigo-500 px-5 py-3">Finalizar</button></Section>}
function Section({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section><h2 className="text-2xl font-black">{title}</h2><p className="mb-5 mt-2 text-sm text-slate-500">{sub}</p>{children}</section>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-2xl border border-slate-800 bg-slate-900/70 p-5 ${className}`}>{children}</div>}
function Metric({label,value}:{label:string;value:string}){return <Card><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-2xl font-black">{value}</div></Card>}
function Empty({text}:{text:string}){return <Card><p className="text-sm text-slate-400">{text}</p></Card>}
