export type PlanTask={id:string;date:string;kind:'lesson'|'practice'|'review'|'essay'|'simulation';subject?:string;topic?:string;durationMin:number;priority:number};
export const PLAN_START='2026-08-26'; export const EXAM_DATE='2026-10-18';
export function dateKey(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function planDay(d=new Date()){const a=new Date(`${PLAN_START}T00:00:00`),b=new Date(`${dateKey(d)}T00:00:00`);return Math.floor((b.getTime()-a.getTime())/86400000)+1}
export function planWeek(d=new Date()){return Math.ceil(planDay(d)/7)}
export function studyWindow(d=new Date()){const n=d.getHours()*60+d.getMinutes(); if(n<960)return 'today'; if(n>=1260)return 'tomorrow'; return 'now'}

const editalTopics:Record<string,string[]>= {
'Matemática':['Números naturais, inteiros, racionais, irracionais, reais e complexos','Equações de 1º, 2º e 3º graus','Razão, proporção e regra de três','Porcentagem','Geometria plana','Geometria espacial','Geometria analítica','Trigonometria','Combinatória e probabilidade','Sistemas lineares, matrizes e determinantes','Funções','Polinômios','Progressões aritmética e geométrica','Matemática financeira','Estatística','Números complexos'],
'Física':['Grandezas escalares e vetoriais, SI, notação científica e análise dimensional','Cinemática escalar e vetorial','Movimento uniforme, uniformemente variado e circular','Queda livre e lançamentos','Leis de Newton, forças e plano inclinado','Estática, equilíbrio e momento de força','Trabalho, energia e potência','Conservação da energia, quantidade de movimento e colisões','Gravitação universal e leis de Kepler','Pressão, densidade e princípios de Pascal, Arquimedes e Stevin','Vasos comunicantes e manômetros','Calor, temperatura e dilatação térmica','Capacidade térmica, calor específico e equilíbrio térmico','Mudanças de estado e transmissão de calor','Leis da termodinâmica, máquinas térmicas e rendimento','Gases ideais e transformações gasosas','Reflexão e refração','Espelhos, lentes e formação de imagens','Ondas, parâmetros, reflexão, refração, difração e interferência','Ondas estacionárias e fenômenos sonoros','Carga, Lei de Coulomb, campo e potencial elétrico','Capacitância, corrente, resistência e tensão','Eletrização e Leis de Ohm','Associação de resistores, potência, energia e efeito Joule','Eletromagnetismo, campo e força magnética'],
'Química':['Estados físicos da matéria, misturas e transformações','Modelos atômicos, distribuição eletrônica, íons e semelhanças atômicas','Tabela periódica e propriedades periódicas','Ligações iônica, metálica e covalente','Geometria e polaridade molecular','Forças intermoleculares e propriedades físicas','Massa atômica, massa molecular, mol e massa molar','Fórmulas centesimal, mínima e molecular','Gases e variáveis de estado','Misturas gasosas e pressões parciais','Ionização, dissociação e eletrólitos','Ácidos, bases, sais e óxidos','Reações e balanceamento','Propriedades dos líquidos e dispersões','Propriedades coligativas e solubilidade','Concentração, diluição e mistura de soluções','Leis de Lavoisier e Proust','Estequiometria','Radioatividade e meia-vida','Termoquímica e Lei de Hess','Cinética química','Equilíbrio químico e Le Chatelier','Equilíbrios iônicos, pH, pOH, hidrólise, Kps e tampões','Eletroquímica e Lei de Faraday','Química orgânica, funções, isomeria e estereoquímica','Reações orgânicas','Petróleo, óleos, gorduras, sabões, detergentes e biodiesel','Acidez, basicidade e polímeros'],
'Biologia':['Origem da vida e teorias evolutivas','Reinos, nomenclatura e classificação dos seres vivos','Invertebrados e cordados','Bioquímica da célula','Teoria celular, procariontes e eucariontes','Células vegetal e animal, estruturas e funções','Divisão celular, fotossíntese, respiração e fermentação','Histologia animal e vegetal','Anatomofisiologia: digestório, respiratório, circulatório e excretório','Sistema osteomuscular e órgãos dos sentidos','Homeostase, hormônios e sistema nervoso','Reprodução sexuada e assexuada','Partenogênese, pedogênese e neotenia','Reprodução humana e gametogênese','Fecundação e embriologia','Leis de Mendel e hereditariedade','Disjunção cromossômica, retrocruzamento e heredogramas','Tri e poliibridismo e probabilidades genéticas','Pleiotropia, alelos múltiplos, grupos sanguíneos e interação gênica','Ligação ao sexo, doenças hereditárias e genética de populações','Ecossistemas, populações, pirâmides ecológicas e biomas','Biosfera, adaptações e equilíbrio ecológico','Ciclos biogeoquímicos','Poluição ambiental','Doenças, profilaxia e saúde','Protozooses, verminoses, doenças bacterianas e micoses','Vírus'],
'Língua Portuguesa':['Leitura e interpretação de textos','Morfologia e classes de palavras','Flexão, concordância e regência','Formação de palavras','Sintaxe: período simples e composto','Sintaxe de regência','Sintaxe de colocação','Pontuação','Acentuação'],
'Literatura Portuguesa e Brasileira':['Movimentos literários portugueses e brasileiros','Autores e obras representativas','Quarto de despejo — Carolina Maria de Jesus','Angústia — Graciliano Ramos','Quincas Borba — Machado de Assis','Marília de Dirceu — Tomás Antônio Gonzaga','Alguma poesia — Carlos Drummond de Andrade'],
'Redação':['Fidelidade ao tema','Planejamento e construção textual','Coerência e coesão','Correção em língua portuguesa','Argumentação e abordagem criativa do tema']
};
const subjects=Object.keys(editalTopics);
export function buildDailyTasks(date=new Date()):PlanTask[]{const day=planDay(date);if(day<1||day>54)return[];const week=planWeek(date);const primary=subjects[(day-1)%subjects.length];const topic=editalTopics[primary][Math.floor((day-1)/subjects.length)%editalTopics[primary].length];const secondary=subjects[day%subjects.length];const topic2=editalTopics[secondary][Math.floor((day-1)/subjects.length)%editalTopics[secondary].length];const tasks:PlanTask[]=[{kind:'lesson',subject:primary,topic,durationMin:35,priority:90},{kind:'practice',subject:primary,topic,durationMin:30,priority:95},{kind:'lesson',subject:secondary,topic:topic2,durationMin:30,priority:88},{kind:'practice',subject:secondary,topic:topic2,durationMin:20,priority:93}];if(week>=2)tasks.push({kind:'review',subject:primary,topic,durationMin:20,priority:85});if(day%7===0)tasks.push({kind:'essay',subject:'Redação',topic:editalTopics['Redação'][(week-1)%editalTopics['Redação'].length],durationMin:60,priority:100});if(week>=4&&day%7===0)tasks.push({kind:'simulation',topic:`Simulado completo — semana ${week}`,durationMin:120,priority:100});return tasks.map((x,i)=>({...x,id:`${dateKey(date)}-${i}`}))}
export function editalCoverage(){return Object.fromEntries(subjects.map(s=>[s,editalTopics[s].length]));}
