/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as LembreteRouteImport } from './routes/lembrete'
import { Route as RedacaoRouteImport } from './routes/redacao'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as ApiCorrigirRedacaoRouteImport } from './routes/api/corrigir-redacao'
import { Route as ApiTutorRouteImport } from './routes/api/tutor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const LembreteRoute = LembreteRouteImport.update({
  id: '/lembrete',
  path: '/lembrete',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacaoRoute = RedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrigirRedacaoRoute = ApiCorrigirRedacaoRouteImport.update({
  id: '/api/corrigir-redacao',
  path: '/api/corrigir-redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/lembrete': typeof LembreteRoute
  '/redacao': typeof RedacaoRoute
  '/tutor': typeof TutorRoute
  '/api/corrigir-redacao': typeof ApiCorrigirRedacaoRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/lembrete': typeof LembreteRoute
  '/redacao': typeof RedacaoRoute
  '/tutor': typeof TutorRoute
  '/api/corrigir-redacao': typeof ApiCorrigirRedacaoRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exercicios': typeof ExerciciosRoute
  '/lembrete': typeof LembreteRoute
  '/redacao': typeof RedacaoRoute
  '/tutor': typeof TutorRoute
  '/api/corrigir-redacao': typeof ApiCorrigirRedacaoRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exercicios'
    | '/lembrete'
    | '/redacao'
    | '/tutor'
    | '/api/corrigir-redacao'
    | '/api/tutor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exercicios'
    | '/lembrete'
    | '/redacao'
    | '/tutor'
    | '/api/corrigir-redacao'
    | '/api/tutor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/exercicios'
    | '/lembrete'
    | '/redacao'
    | '/tutor'
    | '/api/corrigir-redacao'
    | '/api/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExerciciosRoute: typeof ExerciciosRoute
  LembreteRoute: typeof LembreteRoute
  RedacaoRoute: typeof RedacaoRoute
  TutorRoute: typeof TutorRoute
  ApiCorrigirRedacaoRoute: typeof ApiCorrigirRedacaoRoute
  ApiTutorRoute: typeof ApiTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembrete': {
      id: '/lembrete'
      path: '/lembrete'
      fullPath: '/lembrete'
      preLoaderRoute: typeof LembreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacao': {
      id: '/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof RedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corrigir-redacao': {
      id: '/api/corrigir-redacao'
      path: '/api/corrigir-redacao'
      fullPath: '/api/corrigir-redacao'
      preLoaderRoute: typeof ApiCorrigirRedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExerciciosRoute: ExerciciosRoute,
  LembreteRoute: LembreteRoute,
  RedacaoRoute: RedacaoRoute,
  TutorRoute: TutorRoute,
  ApiCorrigirRedacaoRoute: ApiCorrigirRedacaoRoute,
  ApiTutorRoute: ApiTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
