insert into public.subjects(name) values
('Matemática'),('Língua Portuguesa'),('Literatura Portuguesa e Brasileira'),('Biologia'),('Química'),('Física'),('Redação')
on conflict (name) do nothing;

insert into public.topics(subject_id,name,difficulty)
select s.id,v.name,v.difficulty from public.subjects s join (values
('Matemática','Operações básicas',1),('Matemática','Números inteiros',1),('Matemática','Números decimais',1),('Matemática','Frações',1),('Matemática','Frações equivalentes',1),('Matemática','MMC',1),('Matemática','Expressões numéricas',1),('Matemática','Porcentagem',2),('Matemática','Razão e proporção',2),('Matemática','Regra de três',2),('Matemática','Equações',2),('Matemática','Sistemas',3),('Matemática','Funções',3),('Matemática','Geometria',3),('Matemática','Estatística',3),('Matemática','Probabilidade',3),('Matemática','Análise combinatória',4),
('Língua Portuguesa','Compreensão e interpretação de textos',1),('Língua Portuguesa','Informações explícitas e implícitas',1),('Língua Portuguesa','Tema e ideia principal',1),('Língua Portuguesa','Vocabulário pelo contexto',1),('Língua Portuguesa','Substantivo e artigo',1),('Língua Portuguesa','Adjetivo e numeral',1),('Língua Portuguesa','Pronomes',1),('Língua Portuguesa','Verbos',1),('Língua Portuguesa','Advérbios',1),('Língua Portuguesa','Preposições e conjunções',1),('Língua Portuguesa','Análise sintática',2),('Língua Portuguesa','Termos da oração',2),('Língua Portuguesa','Período simples e composto',2),('Língua Portuguesa','Coordenação e subordinação',3),('Língua Portuguesa','Pontuação',2),('Língua Portuguesa','Concordância',3),('Língua Portuguesa','Regência e crase',3),('Língua Portuguesa','Colocação pronominal',3),('Língua Portuguesa','Semântica',2),('Língua Portuguesa','Figuras de linguagem',2),
('Literatura Portuguesa e Brasileira','Gêneros literários',1),('Literatura Portuguesa e Brasileira','Escolas literárias',2),('Literatura Portuguesa e Brasileira','Características literárias',2),('Literatura Portuguesa e Brasileira','Autores e obras',3),('Literatura Portuguesa e Brasileira','Interpretação literária',3),
('Biologia','Organização da vida',1),('Biologia','Célula',1),('Biologia','Procariontes e eucariontes',1),('Biologia','Organelas',1),('Biologia','Membrana',1),('Biologia','Metabolismo',2),('Biologia','Divisão celular',2),('Biologia','Genética',3),('Biologia','Evolução',3),('Biologia','Ecologia',3),('Biologia','Fisiologia',3),('Biologia','Reprodução',3),('Biologia','Microbiologia',3),('Biologia','Botânica',3),('Biologia','Zoologia',3),('Biologia','Temas ambientais',2),
('Química','Matéria',1),('Química','Propriedades da matéria',1),('Química','Substâncias e misturas',1),('Química','Separação de misturas',1),('Química','Estrutura atômica',1),('Química','Número atômico e número de massa',1),('Química','Tabela periódica',2),('Química','Ligações químicas',2),('Química','Funções inorgânicas',2),('Química','Reações químicas',2),('Química','Balanceamento',2),('Química','Mol e estequiometria',3),('Química','Soluções',3),('Química','Gases',3),('Química','Termoquímica',3),('Química','Equilíbrio',4),('Química','Eletroquímica',4),('Química','Química orgânica',3),
('Física','Grandezas e unidades',1),('Física','Movimento',1),('Física','Velocidade',1),('Física','Aceleração',2),('Física','Gráficos',2),('Física','Força e leis de Newton',2),('Física','Trabalho e energia',2),('Física','Potência',2),('Física','Quantidade de movimento',3),('Física','Gravitação',3),('Física','Hidrostática',3),('Física','Termologia',3),('Física','Óptica',3),('Física','Ondas',3),('Física','Eletricidade',3),('Física','Magnetismo',4)
) as v(subject_name,name,difficulty) on s.name=v.subject_name
on conflict (subject_id,name) do nothing;
